<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'default' => [['_locale'], ['_controller' => 'App\\Controller\\DefaultController::index'], ['_locale' => 'en|fr'], [['text', '/'], ['variable', '/', 'en|fr', '_locale', true]], [], []],
    'localeSwitcher' => [['_locale', 'route', 'locale'], ['route' => null, 'locale' => null, '_controller' => 'App\\Controller\\LocaleSwitcher::index'], ['_locale' => 'en|fr'], [['variable', '/', '[^/]++', 'locale', true], ['variable', '/', '[^/]++', 'route', true], ['text', '/changeLocale'], ['variable', '/', 'en|fr', '_locale', true]], [], []],
    'app_register' => [['_locale'], ['_controller' => 'App\\Controller\\RegisterController::register'], ['_locale' => 'en|fr'], [['text', '/register'], ['variable', '/', 'en|fr', '_locale', true]], [], []],
    'app_login' => [['_locale'], ['_controller' => 'App\\Controller\\SecurityController::login'], ['_locale' => 'en|fr'], [['text', '/login'], ['variable', '/', 'en|fr', '_locale', true]], [], []],
    'app_logout' => [['_locale'], ['_controller' => 'App\\Controller\\SecurityController::logout'], ['_locale' => 'en|fr'], [['text', '/logout'], ['variable', '/', 'en|fr', '_locale', true]], [], []],
    'app_profile' => [['_locale'], ['_controller' => 'App\\Controller\\UserController::edit'], ['_locale' => 'en|fr'], [['text', '/profile'], ['variable', '/', 'en|fr', '_locale', true]], [], []],
    'app_user_edit' => [['_locale', 'id'], ['_controller' => 'App\\Controller\\UserController::edit'], ['_locale' => 'en|fr'], [['variable', '/', '[^/]++', 'id', true], ['text', '/profile'], ['variable', '/', 'en|fr', '_locale', true]], [], []],
    'app_profile_avatar' => [['_locale'], ['_controller' => 'App\\Controller\\UserController::changeAvatar'], ['_locale' => 'en|fr'], [['text', '/avatar'], ['variable', '/', 'en|fr', '_locale', true]], [], []],
    'index' => [[], ['path' => '/en', 'controller' => 'App\\Controller\\DefaultController::index', '_controller' => 'Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController'], [], [['text', '/']], [], []],
];
